### ISSUE TITLE
[FEATURE] Add GitHub Action to Automatically Comment on Pull Requests

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/DTaaS#1276]
## Summary

I’d like to request the addition of a GitHub Action workflow that automatically posts comments on pull requests. This will streamline code review feedback, enable automated review bots, and help maintainers provide consistent communication on PRs.

## Proposed Implementation

Add a workflow (e.g., `.github/workflows/auto-pr-comment.yml`) using the [peter-evans/create-or-update-comment](https://github.com/peter-evans/create-or-update-comment) GitHub Action.

**Example Workflow:**

```yaml
name: Auto PR Comment
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Post a comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            <!-- Copilot Chat Review -->
            Your Copilot Chat review or feedback goes here.
```

## Benefits

- Automates routine feedback and review comments.
- Ensures consistent communication for contributors.
- Can be extended to integrate with bots, Copilot, or other review tools.
