### ISSUE TITLE
Run DTaaS with localhost domain name

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/DTaaS#301]
The DTaaS software must run within user computer. The domain name of the web server as mentioned in [trial install](https://into-cps-association.github.io/DTaaS/development/admin/trial.html) shall be `localhost`.

This is related to issue #31

**Comment by prasadtalasila** [comment]
This should work with the following configuration:

**env.js**
```js
window.env = {
  REACT_APP_ENVIRONMENT: 'dev',
  REACT_APP_URL: 'http://localhost:4000/',
  REACT_APP_URL_BASENAME: '',
  REACT_APP_URL_DTLINK: '/lab',
  REACT_APP_URL_LIBLINK: '',
  REACT_APP_WORKBENCHLINK_TERMINAL: '/terminals/main',
  REACT_APP_WORKBENCHLINK_VNCDESKTOP: '/tools/vnc/?password=vncpassword',
  REACT_APP_WORKBENCHLINK_VSCODE: '/tools/vscode/',
  REACT_APP_WORKBENCHLINK_JUPYTERLAB: '/lab',
  REACT_APP_WORKBENCHLINK_JUPYTERNOTEBOOK: '',

  REACT_APP_CLIENT_ID: '1be55736756190b3ace4c2c4fb19bde386d1dcc748d20b47ea8cfb5935b8446c',
  REACT_APP_AUTH_AUTHORITY: 'https://gitlab.com/',
  REACT_APP_REDIRECT_URI: 'http://localhost:4000/Library',
  REACT_APP_LOGOUT_REDIRECT_URI: 'http://localhost:4000/',
  REACT_APP_GITLAB_SCOPES: 'openid profile read_user read_repository api',
};
```

**fileConfig.yml**

```yml
http:
  routers:
    dtaas:
      entryPoints:
        - http
      rule: 'Host(`localhost`)'
      middlewares:
        - basic-auth
      service: dtaas

    user1:
      entryPoints:
        - http
      rule: 'Host(`localhost`) && PathPrefix(`/user1`)'
      middlewares:
        - basic-auth
      service: user1

    user2:
      entryPoints:
        - http
      rule: 'Host(`localhost`) && PathPrefix(`/user2`)'
      middlewares:
        - basic-auth
      service: user2

    libms:
      entryPoints:
        - http
      rule: 'Host(localhost`) && PathPrefix(`/lib`)'
      service: libms


  # Middleware: Basic authentication
  middlewares:
    basic-auth:
      basicAuth:
        usersFile: "/etc/traefik/auth"
        removeHeader: true


  services:
    dtaas:
      loadBalancer:
        servers:
          - url: "http://localhost:4000"

    user1:
      loadBalancer:
        servers:
          - url: "http://localhost:8090"

    user2:
      loadBalancer:
        servers:
          - url: "http://localhost:8091"

    libms:
      loadBalancer:
        servers:
          - url: "http://localhost:4001"
```

**lib**

```ini
PORT='4001'
MODE='local'
LOCAL_PATH ='filepath'
LOG_LEVEL='debug'
APOLLO_PATH='/lib'
GRAPHQL_PLAYGROUND='true'
```

filenames: `deploy/config/client/env.js.local` and `deploy/config/gateway/fileConfig.yml.local` and `deploy/config/lib.local`.

Please add `deploy/localhost.sh` to setup the install on `localhost`.
