### ISSUE TITLE
Embed grafana in website iframe

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/DTaaS#38]
Embedding grafana in iframe of website doesn't work. The setup is as follows.

### website configuration:
```env
window.env = {
  REACT_APP_ENVIRONMENT: 'test',
  REACT_APP_URL_LIB: 'http://foo.com/user1/tree?',
  REACT_APP_URL_DT: 'http://foo.com/user1/lab',
  REACT_APP_URL_WORKBENCH: 'https://foo.com/vis',
};
```

### service setup:
| service | URL |
|:---|:---|
| website | localhost:4000 |
| mlworkspace | localhost:8090 |
| grafana | localhost:3000 |

### The gateway configuration:
```yaml
http:
  routers:
    dtaas:
      entryPoints:
        - http
      rule: 'Host(`foo.com`)'
      middlewares:
        - basic-auth
      service: dtaas

    user1:
      entryPoints:
        - http
      rule: 'Host(`foo.com`) && PathPrefix(`/user1`)'
      middlewares:
        - basic-auth
      service: user1

    vis:
      entryPoints:
        - http
      rule: 'Host(`foo.com`) && PathPrefix(`/vis`)'
      service: grafana


  # Middleware: Basic authentication
  middlewares:
    basic-auth:
      basicAuth:
        usersFile: "/etc/traefik/auth"


  services:
    dtaas:
      loadBalancer:
        servers:
          - url: "http://localhost:4000"

    user1:
      loadBalancer:
        servers:
          - url: "http://localhost:8090"

    grafana:
      loadBalancer:
        servers:
          - url: "http://localhost:3000"
```

With the above setup, the following work:
* https://foo.com
* https://foo.com/library
* https://foo.com/digitaltwins
* https://foo.com/vis

The following doesn't work:
* https://foo.com/workbench

Not sure if this is related to issue #31.
