### ISSUE TITLE
basename to the application

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/DTaaS#53]
It might be a good occasion to provide for flexible application paths. 

So far we are assuming that the application is always hosted at `REACT_APP_URL`. Most often, the applications are hosted at certain URL paths, for example `odin.cps.digit.au.dk/mediawiki`. In this case, mediawiki is hosted at that URL which has odin.cps.digit.au.dk as hostname and mediawiki as basepath.

It is possible to make react apps work that way too. For example, we can host DTaaS at `REACT_APP_URL/dtaas`. Here `dtaas` is the application basename and becomes the prefix for all the react router paths. React BrowserRouter has [basename](https://reactrouter.com/en/main/routers/create-browser-router#basename) attribute that makes it possible. While doing this, it might be appropriate to separate out the [routes](https://reactrouter.com/en/main/routers/create-browser-router#routes) array so that the createBrowserRouter() function call looks more readable.

Suggested refactoring is:
```
const routes =   [
    path: '/',
    element: <SignIn />,
  },
....
  {
    path: 'workbench',
    element: (
      <PrivateRoute>
        <WorkBench />
      </PrivateRoute>
    ),
  },
];
const router = createBrowserRouter(routes, {
  basename: "/app", //this basename has to come from env.js
});
```

**Comment by Omarley7** [comment]
It seems very possible.

Would you like the basename variable to be `REACT_APP_BASENAME` or `REACT_APP_URL_BASENAME`  as well? I'm thinking if the base name can be used in multiple contexts

**Comment by prasadtalasila** [comment]
We could use either REACT_APP_URL_BASENAME or REACT_APP_URL_PATH. Given that React Router uses REACT_APP_URL_BASENAME, this option seems appropriate. Do you have any other suggestions?

**Comment by Omarley7** [comment]
I think REACT_APP_URL_BASENAME is fine. Is it mandatory, or should we handle it as optional? (thinking `''` would indicate no basename)

**Comment by prasadtalasila** [comment]
> I think REACT_APP_URL_BASENAME is fine. Is it mandatory, or should we handle it as optional? (thinking '' would indicate no basename)

Yes and please make it optional. The envUtils.js can set a default value if there is no matching variable in env.js.

**Comment by Omarley7** [comment]
I've made a local PR. I just need to figure out how to handle the E2E tests dynamically. It works if I hardcode in the basename.
https://github.com/Omarley7/DTaaS-Bachelor-new-GUI/pull/54

**Comment by prasadtalasila** [comment]
done in [011c40f](https://github.com/INTO-CPS-Association/DTaaS/commit/011c40f013666ac1ea79f63cfc81b3989a6b8f3e). But the `REACT_APP_URL_BASENAME: 'dtaas'` works only if ` REACT_APP_URL: 'localhost'`. It doesn't work for any other URL. For example, it doesn't work for ` REACT_APP_URL: 'https://example.com/'`.

**Comment by prasadtalasila** [comment]
This works as expected. The point to note is that the traefik config should not be changed. For example, to host DTaaS at `https://foo.com/sandbox`, the following traefik configuration is needed.

```yml
http:
  routers:
    dtaas:
      entryPoints:
        - http
      rule: 'Host(`foo.com`)'
      middlewares:
        - basic-auth
      service: dtaas

    user1:
      entryPoints:
        - http
      rule: 'Host(`foo.com`) && PathPrefix(`/user1`)'
      middlewares:
        - basic-auth
      service: user1

    user2:
      entryPoints:
        - http
      rule: 'Host(`foo.com`) && PathPrefix(`/user2`)'
      middlewares:
        - basic-auth
      service: user2

```

Note the absence of `sandbox` basepath  in the dtaas route.
