### ISSUE TITLE
Update install instructions

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/DTaaS#55]
Update installation procedures and instructions in `deploy/` for the latest codebase.

**Comment by prasadtalasila** [comment]
issue #41 needs to be resolved to solve the problem highlighted in this issue.

**Comment by prasadtalasila** [comment]
Update install instructions to host the application at a basepath. See the clarification mentioned in issue #53. The basepath needs to be reflected in all the workspace relative URLs too. The relative URLs are hardcoded in the codebase. So there is no option but to update the relative URLs of workspaces to include the basepath.

**Comment by prasadtalasila** [comment]
The updates required to make the application work with basepath (say dtaas):
```
http:
  routers:
    dtaas:
      entryPoints:
        - http
      rule: 'Host(`foo.com`)' #remember, there is no basepath for this rule
      middlewares:
        - basic-auth
      service: dtaas

    user1:
      entryPoints:
        - http
      rule: 'Host(`foo.com`) && PathPrefix(`/dtaas/user1`)'
      middlewares:
        - basic-auth
      service: user1

    user2:
      entryPoints:
        - http
      rule: 'Host(`localhost`) && PathPrefix(`/dtaas/user2`)'
      middlewares:
        - basic-auth
      service: user2

    vis:
      entryPoints:
        - http
      rule: 'Host(`localhost`) && PathPrefix(`/vis`)'
      service: grafana

    lib:
      entryPoints:
        - http
      rule: 'Host(`localhost`) && PathPrefix(`/dtaas/lib`)'
      service: lib

  # Middleware: Basic authentication
  middlewares:
    basic-auth:
      basicAuth:
        usersFile: '/etc/traefik/auth'
        removeHeader: true

  services:
    dtaas:
      loadBalancer:
        servers:
          - url: 'http://localhost:4000'

    user1:
      loadBalancer:
        servers:
          - url: 'http://localhost:8090'

    user2:
      loadBalancer:
        servers:
          - url: 'http://localhost:8091'

    grafana:
      loadBalancer:
        servers:
          - url: 'http://localhost:3000'

    lib:
      loadBalancer:
        servers:
          - url: 'http://localhost:4001'
```
