### ISSUE TITLE
Gitlab integration into installation

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/DTaaS#892]
The new development in react client is pushing towards integrating Gitlab CI/CD integration. Thus there is a need to integrate gitlab and gitlab runner into the standard installation setup. A suggested integration structure is

![new-installation](https://github.com/user-attachments/assets/330220f8-5e24-4ccb-8d67-2df667cdfb4a)

Of the given figure, the gitlab and runner containers are to be put into one docker compose package. The rest of containers need to be put into another docker compose package. The task on putting rest of containers into one docker compose is already complete. Only the gitlab and runner integration is pending.

**Comment by prasadtalasila** [comment]
@aryanpingle this issue tracks your tasks. Please comment here if you require any clarification.

**Comment by aryanpingle** [comment]
[gitlab.js](https://github.com/INTO-CPS-Association/DTaaS/blob/a335ae47898d932dcf0e11559ca1883ca8068641/deploy/services/gitlab.js) currently uses the configuration in [gitlab.yml](https://github.com/INTO-CPS-Association/DTaaS/blob/a335ae47898d932dcf0e11559ca1883ca8068641/deploy/services/gitlab.yml), so I'm thinking we can just use the `DTaaS/docker/.env` file with a new `compose.gitlab.yml` file like so:

```yml
# docker run -d \
#   --hostname ${gitlabConfig.hostname} \
#   --env EXTERNAL_URL=${gitlabConfig.url} \
#   --publish ${gitlabConfig.port}:80 \
#   --name gitlab \
#   --restart always \
#   --volume ${gitlabConfig.homedir}/config:/etc/gitlab:Z \
#   --volume ${gitlabConfig.homedir}/logs:/var/log/gitlab:Z \
#   --volume ${gitlabConfig.homedir}/data:/var/opt/gitlab:Z \
#   --shm-size 256m \
#   gitlab/gitlab-ce:16.4.1-ce.0

version: '3'
services:
  gitlab:
    image: gitlab/gitlab-ce:16.4.1-ce.0
    hostname: ${SERVER_DNS}
    restart: always
    volumes:
      - ${VAGRANT_GITLAB_DIR}/config:/etc/gitlab:Z
      - ${VAGRANT_GITLAB_DIR}/logs:/var/log/gitlab:Z
      - ${VAGRANT_GITLAB_DIR}/data:/var/opt/gitlab:Z
    shm_size: "256m"
    ports:
      - "8969:80" # from gitlab.yml
    environment:
      - EXTERNAL_URL=${SERVER_DNS}/gitlab
```

`gitlab.yml` contains this:

```yml
homedir: "/home/vagrant/DTaaS/deploy/services/gitlab" #no spaces in the path
```

Should we be using `${DTAAS_DIR}/deploy/services/gitlab` instead? If not, we can just declare it (and port 8969) as a variable in this `.env` file
